name: app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  json_annotation: ^4.4.0
  flutter_bloc: any
  bloc:
  provider: ^5.0.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  rxdart: ^0.27.3
  dio: ^4.0.4
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  smooth_page_indicator: ^1.0.0+2
  permission_handler: ^6.1.3
  fluttertoast: ^8.0.9
  flushbar:
  firebase_auth: ^3.3.11              #FIREBASE USER AUTH PHONE VERIFICATION
  page_transition: ^2.0.5          # PAGE TRANSITION
  google_maps_flutter: ^2.1.3      # GOOGLE MAP
  firebase_core: any               # FIREBASE CORE
  flutter_spinkit: ^5.1.0        # PROGRESS INDICATOR
  cached_network_image: ^3.2.0     #Image
  photo_view: ^0.13.0
  image_cropper: ^1.3.1            #IMAGE CROPPER
  image_picker: ^0.8.4+11         # IMAGE PICK FROM GALERRY & CAMERA
  flutter_country_picker: ^0.1.6   # phone country code pickerq 11  ยง`
  firebase_storage: any         # FIREBASE storage
  cloud_firestore: any         # FIREBASE realtime db
  firebase_messaging: ^10.0.1       #FIREBASE messaging
  flutter_local_notifications: ^9.4.0 #LOCALNOTIFICATIONS
  intl: ^0.17.0
  flutter_datetime_picker: any
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
  collection: ^1.14.13
  sticky_grouped_list: ^2.1.0
  google_maps_place_picker: ^2.1.0-nullsafety.3
  webview_flutter: any
  flutter_webview_plugin: ^0.4.0

  #son_serializable: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Gibson
      fonts:
        - asset: assets/fonts/gibson-bold.ttf
          weight: 700
        - asset: assets/fonts/Gibson-Regular.ttf
          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
