-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTZBBtY0yE2KRHoJ2
WBWem7EUcVupGAZ9l8kaAPHTVhugCgYIKoZIzj0DAQehRANCAARijtm47IaOjB+t
VqQJXKsteSYTE+sBtk5F4vE2C8S//jC2JjJhJyb+gnOUdkxE6cdPvZ6ZuxjovUe0
YgNVpJWF
-----END PRIVATE KEY-----